### PR TITLE
Move logging listeners into separate maven submodules

### PR DESCRIPTION
**Pull request by jkebinger**
This moves the maven submodules for log4j etc into their own submodules so that users can depend on just the one they need (and not get CVE warnings for having log4j 1 on the classpath)

### CODE REVIEW

**Comment by jhaber** [comment]
Not against moving to a different module, but all the deps were optional so there’s nothing extra on the classpath and users shouldn’t get any CVE warnings (or at least I’d be surprised if that happened)

**Comment by jkebinger** [comment]
Dependabot is mentioning the CVEs for log4j. I didn't really notice the presence of the optional flag in maven until i was already waist deep in splitting up the project, so I didn't actually grok what it does. 'tis done now :/

**Comment by jhaber** [comment]
👍 sounds good. Was dependabot yelling at this repo itself, or also people using this repo?

**Comment by jkebinger** [comment]
It was this repo :(

**Comment by jhaber** [comment]
Gotcha, I wouldn't expect that to go away unfortunately. We could drop support for log4j1 if it looks like no one is using that artifact (now that it's a separate artifact we should be able to track that to some extent)

**Comment by jkebinger** [comment]
Yep, old log4j is never getting fixed. This way we can avoid even having to explain that it won't actually matter to a customer not using it

**Pull request merged**
